name: Sync meta-rules-dat/meta to geo-rules/main

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时执行一次（根据需要修改）
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self (geo-rules repo)
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone meta-rules-dat repo (meta branch)
        run: |
          git clone --single-branch --branch meta git@github.com:MetaCubeX/meta-rules-dat.git upstream-meta
          rm -rf * .github .git
          cp -r upstream-meta/* .
          rm -rf upstream-meta
        shell: bash

      - name: Set git identity
        run: |
          git config user.name "vansour"
          git config user.email "vansoursheng@gmail.com"

      - name: Commit and push changes to geo-rules main
        run: |
          git init
          git remote add origin git@github.com:vansour/geo-rules.git
          git checkout -b main
          git add .
          git commit -m "Auto sync from meta-rules-dat/meta"
          git push -f origin main
