name: Sync Meta Rules

on:
  schedule:
    - cron: '0 2 * * *'  # 每天定时
  workflow_dispatch:

jobs:
  sync-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install unzip and git
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Download meta.zip
        run: |
          curl -L -o meta.zip https://github.com/MetaCubeX/meta-rules-dat/archive/refs/heads/meta.zip

      - name: Unzip meta.zip
        run: |
          unzip meta.zip
          mv meta-rules-dat-meta extracted

      - name: Configure Git
        run: |
          git config --global user.name "vansour"
          git config --global user.email "vansoursheng@gmail.com"

      - name: Clone target repo with token
        run: |
          git clone https://vansour:${{ secrets.GH_TOKEN }}@github.com/vansour/geo-rules.git target-repo

      - name: Copy new files
        run: |
          rm -rf target-repo/*
          cp -r extracted/* target-repo/

      - name: Commit & push changes
        run: |
          cd target-repo
          git add .
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto-sync from meta-rules-dat"
            git push https://vansour:${{ secrets.GH_TOKEN }}@github.com/vansour/geo-rules.git main
          fi
