name: Sync Meta Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 运行（可自定义）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (空 repo 用于初始化 workspace)
      uses: actions/checkout@v4

    - name: Install unzip and git
      run: sudo apt-get update && sudo apt-get install -y unzip git

    - name: Download meta.zip
      run: curl -L -o meta.zip https://github.com/MetaCubeX/meta-rules-dat/archive/refs/heads/meta.zip

    - name: Unzip meta.zip
      run: unzip meta.zip

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone target repo
      run: |
        git clone git@github.com:vansour/geo-rules.git target-repo
        rsync -av --delete meta-rules-dat-meta/ target-repo/
      shell: bash

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "vansour"
        git config user.email "vansoursheng@gmail.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Sync from MetaCubeX/meta-rules-dat"
          git push origin main
        else
          echo "No changes to commit"
        fi
