name: Sync meta-rules-dat/meta → geo-rules/main

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout geo-rules repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Clone meta-rules-dat (meta branch)
        run: |
          git clone --single-branch --branch meta \
            git@github.com:MetaCubeX/meta-rules-dat.git \
            /tmp/upstream-meta

      - name: Clean working directory
        run: |
          find . -mindepth 1 \
            -not -path './.github*' \
            -not -path './.git*' \
            -exec rm -rf {} +

      - name: Copy files from upstream-meta
        run: |
          rsync -av --delete --exclude='.git' /tmp/upstream-meta/ ./

      - name: Set Git identity
        run: |
          git config user.name "vansour"
          git config user.email "vansoursheng@gmail.com"

      - name: Use SSH for origin
        run: |
          git remote set-url origin git@github.com:vansour/geo-rules.git

      - name: Commit & Force-push to main
        run: |
          git add --all
          git commit -m "Auto-sync from MetaCubeX/meta-rules-dat@meta" --allow-empty
          git push origin HEAD:main --force
