name: Sync Meta Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest  # 需要 ubuntu runner 来启动容器
    container:
      image: debian:12  # ✅ 使用官方 Debian 12 容器镜像

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git unzip curl openssh-client rsync

    - name: Download meta.zip
      run: curl -L -o meta.zip https://github.com/MetaCubeX/meta-rules-dat/archive/refs/heads/meta.zip

    - name: Unzip meta.zip
      run: unzip meta.zip

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone target repo and sync
      run: |
        git clone git@github.com:vansour/geo-rules.git target-repo
        UNZIP_DIR=$(find . -maxdepth 1 -type d -name "meta-rules-dat-*")
        rsync -av --delete "$UNZIP_DIR/" target-repo/

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "vansour"
        git config user.email "vansoursheng@gmail.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Sync from MetaCubeX/meta-rules-dat"
          git push origin main
        else
          echo "No changes to commit"
